import React, { createContext, useContext, useState } from 'react';

// Define the type for the language context
type LanguageContextType = {
  language: string;
  setLanguage: (language: string) => void;
  t: (key: string) => string;
};

// Create the context with default values
const LanguageContext = createContext<LanguageContextType>({
  language: 'de',
  setLanguage: () => {},
  t: () => '',
});

// Translation dictionary
const translations: { [key: string]: { [key: string]: string } } = {
  en: {
    heroTitle1: 'We empower',
    heroTitle2: 'female mobility.',
    heroSubtitle: 'Join our community for safe and reliable rides, driven by women, for women.',
    heroButton: 'Join FemRide',
    servicesTitle: 'Why choose FemRide?',
    servicesSubtitle: 'Our services are designed with your safety and comfort in mind.',
    service1Title: 'Safety First',
    service1Description: 'All our drivers are certified and background-checked to ensure your safety.',
    service2Title: 'Comfortable Rides',
    service2Description: 'Enjoy a relaxed and pleasant journey in a vehicle that suits your needs.',
    service3Title: 'Female Community',
    service3Description: 'Connect with a community of female drivers and riders who understand your needs.',
    aboutTitle: 'About FemRide',
    aboutText1: 'FemRide is more than just a ride-sharing app. We are a community dedicated to providing safe, reliable, and comfortable transportation for women, by women.',
    aboutText2: 'Our mission is to empower women by creating economic opportunities for female drivers and offering a secure transportation option for female riders.',
    aboutButton: 'Learn More',
    latestFeaturesTitle: 'Drive with FemRide',
    latestFeaturesText: 'Unlock new opportunities and empower women in your city. Join FemRide as a driver or fleet partner and be part of a movement that values safety, community, and economic growth.',
    faqTitle: 'Frequently Asked Questions',
    faqQuestion1: 'How does FemRide ensure safety?',
    faqAnswer1: 'We conduct thorough background checks on all drivers and provide a platform for riders to rate and review their experiences.',
    faqQuestion2: 'Can I schedule a ride in advance?',
    faqAnswer2: 'Yes, you can schedule rides in advance to ensure you have a ride when you need it.',
    faqQuestion3: 'What types of vehicles are available?',
    faqAnswer3: 'We offer a variety of vehicle options to suit your needs, from standard cars to larger vehicles for groups.',
    contactHeader: 'Contact Us',
    contactTitle: 'Get in Touch',
    contactText1: 'Have questions or need assistance?',
    contactText2: 'We are here to help!',
    contactText3: 'Feel free to reach out to us with any inquiries or feedback.',
    contactText4: 'We value your input and strive to provide the best possible experience.',
    contactText5: 'Contact us today and let us assist you!',
    contactNameLabel: 'Your Name',
    contactNamePlaceholder: 'Enter your name',
    contactEmailLabel: 'Your Email',
    contactEmailPlaceholder: 'Enter your email',
    contactPhoneLabel: 'Your Phone Number (Optional)',
    contactPhonePlaceholder: 'Enter your phone number',
    contactMessageLabel: 'Your Message',
    contactMessagePlaceholder: 'Enter your message',
    contactSubmitButton: 'Send Message',
    contactSubmitting: 'Submitting...',
    contactSuccessTitle: 'Message sent!',
    contactSuccessDesc: 'We\'ll get back to you shortly.',
    contactErrorTitle: 'Error',
    contactErrorDesc: 'There was an error sending your message. Please try again.',
    contactFormSubject: 'Contact Form Submission from',
    contactFormName: 'Name',
    contactFormEmail: 'Email',
    contactFormPhone: 'Phone',
    contactFormPhoneNotSpecified: 'Not specified',
    contactFormMessageLabel: 'Message',
    downloadTitle: 'Download the App',
    downloadSubtitle: 'Experience the convenience and safety of FemRide on your mobile device.',
    downloadButton: 'Download Now',
    footerCopyright: '© 2024 FemRide. All rights reserved.',
    footerTerms: 'Terms of Service',
    footerPrivacy: 'Privacy Policy',
    joinUsSectionHeader: 'Opportunities',
    joinUsSectionTitle: 'Join the FemRide Community',
    joinUsSectionSubtitle: 'Empower women and earn with FemRide.',
    joinUsSectionDescription: 'Become a driver or fleet partner and be part of a movement that values safety, community, and economic growth.',
    forFemaleDrivers: 'For Female Drivers',
    forFemaleDriversDesc: 'Join our network of female drivers and enjoy flexible hours, competitive pay, and a supportive community.',
    forFemaleDriversButton: 'Become a Driver',
    forFleetOperators: 'For Fleet Operators',
    forFleetOperatorsDesc: 'Partner with FemRide and expand your business while supporting female empowerment.',
    forFleetOperatorsButton: 'Partner with Us',
    latestFeaturesSectionTitle: 'Book Your Ride in Advance',
    latestFeaturesSectionText: 'Plan ahead and book your ride in advance with FemRide. Enjoy the convenience of scheduling your transportation and ensuring a safe and reliable journey.',
    
    // Newsletter translations
    newsletterTitle: "Stay Updated",
    newsletterDescription: "Subscribe to our newsletter for the latest FemRide news, updates, and exclusive offers.",
    newsletterEmailPlaceholder: "Your email address",
    newsletterSubmitButton: "Subscribe",
    newsletterSubmitting: "Subscribing...",
    newsletterSuccessTitle: "Thank you for subscribing!",
    newsletterSuccessDesc: "You've been added to our newsletter list.",
    newsletterErrorTitle: "Subscription failed",
    newsletterErrorDesc: "There was an error subscribing to the newsletter. Please try again.",
    newsletterDisclaimer: "By subscribing, you agree to receive emails from FemRide. You can unsubscribe at any time.",
    newsletterSubscriptionRequest: "Newsletter Subscription Request",
    newsletterEmailBody: "Hello,\n\nI would like to subscribe to the FemRide newsletter with my email address: {email}\n\nThank you!",
  },
  de: {
    heroTitle1: 'Wir stärken die',
    heroTitle2: 'weibliche Mobilität.',
    heroSubtitle: 'Treten Sie unserer Community für sichere und zuverlässige Fahrten bei, gefahren von Frauen für Frauen.',
    heroButton: 'FemRide beitreten',
    servicesTitle: 'Warum FemRide wählen?',
    servicesSubtitle: 'Unsere Dienstleistungen sind auf Ihre Sicherheit und Ihren Komfort zugeschnitten.',
    service1Title: 'Sicherheit zuerst',
    service1Description: 'Alle unsere Fahrer sind zertifiziert und hintergrundgeprüft, um Ihre Sicherheit zu gewährleisten.',
    service2Title: 'Komfortable Fahrten',
    service2Description: 'Genießen Sie eine entspannte und angenehme Reise in einem Fahrzeug, das Ihren Bedürfnissen entspricht.',
    service3Title: 'Weibliche Gemeinschaft',
    service3Description: 'Vernetzen Sie sich mit einer Gemeinschaft von Fahrerinnen und Mitfahrerinnen, die Ihre Bedürfnisse verstehen.',
    aboutTitle: 'Über FemRide',
    aboutText1: 'FemRide ist mehr als nur eine Mitfahr-App. Wir sind eine Gemeinschaft, die sich der Bereitstellung sicherer, zuverlässiger und komfortabler Transportmittel für Frauen durch Frauen verschrieben hat.',
    aboutText2: 'Unsere Mission ist es, Frauen zu stärken, indem wir wirtschaftliche Möglichkeiten für Fahrerinnen schaffen und eine sichere Transportmöglichkeit für weibliche Fahrgäste anbieten.',
    aboutButton: 'Mehr erfahren',
    latestFeaturesTitle: 'Fahren Sie mit FemRide',
    latestFeaturesText: 'Erschließen Sie neue Möglichkeiten und stärken Sie Frauen in Ihrer Stadt. Werden Sie Fahrer oder Flottenpartner bei FemRide und seien Sie Teil einer Bewegung, die Sicherheit, Gemeinschaft und Wirtschaftswachstum schätzt.',
    faqTitle: 'Häufig gestellte Fragen',
    faqQuestion1: 'Wie stellt FemRide die Sicherheit sicher?',
    faqAnswer1: 'Wir führen gründliche Hintergrundüberprüfungen aller Fahrer durch und bieten eine Plattform für Fahrgäste, um ihre Erfahrungen zu bewerten und zu überprüfen.',
    faqQuestion2: 'Kann ich eine Fahrt im Voraus planen?',
    faqAnswer2: 'Ja, Sie können Fahrten im Voraus planen, um sicherzustellen, dass Sie eine Fahrt haben, wenn Sie sie benötigen.',
    faqQuestion3: 'Welche Arten von Fahrzeugen stehen zur Verfügung?',
    faqAnswer3: 'Wir bieten eine Vielzahl von Fahrzeugoptionen, die Ihren Bedürfnissen entsprechen, von Standardautos bis hin zu größeren Fahrzeugen für Gruppen.',
    contactHeader: 'Kontaktieren Sie uns',
    contactTitle: 'Nehmen Sie Kontakt auf',
    contactText1: 'Haben Sie Fragen oder benötigen Sie Hilfe?',
    contactText2: 'Wir sind hier, um zu helfen!',
    contactText3: 'Zögern Sie nicht, uns bei Fragen oder Feedback zu kontaktieren.',
    contactText4: 'Wir schätzen Ihren Beitrag und bemühen uns, die bestmögliche Erfahrung zu bieten.',
    contactText5: 'Kontaktieren Sie uns noch heute und lassen Sie sich von uns helfen!',
    contactNameLabel: 'Dein Name',
    contactNamePlaceholder: 'Gib deinen Namen ein',
    contactEmailLabel: 'Deine E-Mail',
    contactEmailPlaceholder: 'Gib deine E-Mail ein',
    contactPhoneLabel: 'Deine Telefonnummer (Optional)',
    contactPhonePlaceholder: 'Gib deine Telefonnummer ein',
    contactMessageLabel: 'Deine Nachricht',
    contactMessagePlaceholder: 'Gib deine Nachricht ein',
    contactSubmitButton: 'Nachricht senden',
    contactSubmitting: 'Wird gesendet...',
    contactSuccessTitle: 'Nachricht gesendet!',
    contactSuccessDesc: 'Wir werden uns in Kürze bei Ihnen melden.',
    contactErrorTitle: 'Fehler',
    contactErrorDesc: 'Beim Senden Ihrer Nachricht ist ein Fehler aufgetreten. Bitte versuche es erneut.',
    contactFormSubject: 'Kontaktformular-Einsendung von',
    contactFormName: 'Name',
    contactFormEmail: 'E-Mail',
    contactFormPhone: 'Telefon',
    contactFormPhoneNotSpecified: 'Nicht angegeben',
    contactFormMessageLabel: 'Nachricht',
    downloadTitle: 'Laden Sie die App herunter',
    downloadSubtitle: 'Erleben Sie den Komfort und die Sicherheit von FemRide auf Ihrem Mobilgerät.',
    downloadButton: 'Jetzt herunterladen',
    footerCopyright: '© 2024 FemRide. Alle Rechte vorbehalten.',
    footerTerms: 'Nutzungsbedingungen',
    footerPrivacy: 'Datenschutzrichtlinie',
    joinUsSectionHeader: 'Möglichkeiten',
    joinUsSectionTitle: 'Treten Sie der FemRide-Community bei',
    joinUsSectionSubtitle: 'Stärken Sie Frauen und verdienen Sie mit FemRide.',
    joinUsSectionDescription: 'Werden Sie Fahrer oder Flottenpartner und seien Sie Teil einer Bewegung, die Sicherheit, Gemeinschaft und Wirtschaftswachstum schätzt.',
    forFemaleDrivers: 'Für Fahrerinnen',
    forFemaleDriversDesc: 'Treten Sie unserem Netzwerk von Fahrerinnen bei und genießen Sie flexible Arbeitszeiten, wettbewerbsfähige Bezahlung und eine unterstützende Community.',
    forFemaleDriversButton: 'Werde Fahrerin',
    forFleetOperators: 'Für Flottenbetreiber',
    forFleetOperatorsDesc: 'Werden Sie Partner von FemRide und erweitern Sie Ihr Geschäft, während Sie die Stärkung von Frauen unterstützen.',
    forFleetOperatorsButton: 'Partner werden',
    latestFeaturesSectionTitle: 'Buchen Sie Ihre Fahrt im Voraus',
    latestFeaturesSectionText: 'Planen Sie im Voraus und buchen Sie Ihre Fahrt im Voraus mit FemRide. Genießen Sie den Komfort, Ihren Transport zu planen und eine sichere und zuverlässige Reise zu gewährleisten.',
    
    // Newsletter translations
    newsletterTitle: "Bleibe auf dem Laufenden",
    newsletterDescription: "Abonniere unseren Newsletter für die neuesten FemRide-Nachrichten, Updates und exklusive Angebote.",
    newsletterEmailPlaceholder: "Deine E-Mail-Adresse",
    newsletterSubmitButton: "Abonnieren",
    newsletterSubmitting: "Wird abonniert...",
    newsletterSuccessTitle: "Vielen Dank für dein Abonnement!",
    newsletterSuccessDesc: "Du wurdest zu unserer Newsletter-Liste hinzugefügt.",
    newsletterErrorTitle: "Abonnement fehlgeschlagen",
    newsletterErrorDesc: "Beim Abonnieren des Newsletters ist ein Fehler aufgetreten. Bitte versuche es erneut.",
    newsletterDisclaimer: "Mit dem Abonnieren erklärst du dich damit einverstanden, E-Mails von FemRide zu erhalten. Du kannst dich jederzeit abmelden.",
    newsletterSubscriptionRequest: "Newsletter-Abonnementanfrage",
    newsletterEmailBody: "Hallo,\n\nIch möchte den FemRide-Newsletter mit meiner E-Mail-Adresse abonnieren: {email}\n\nVielen Dank!",
  },
};

// Create the provider component
export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState('de');

  // Function to translate a given key
  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Create the hook to use the language context
export const useLanguage = () => useContext(LanguageContext);
