
import React from 'react';
import Navbar from '../shared/Navbar';
import { Footer } from '../shared/Footer';

const PrivacyPolicy = () => {
  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      <main className="flex-1 container mx-auto px-4 py-8 max-w-5xl">
        <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>
        <p className="text-gray-600 mb-4">Last updated: April 05, 2025</p>
        
        <div className="prose max-w-none">
          <p>
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          
          <p>
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. If you do not agree with this Privacy Policy in general or any part of it, you should not access the Websites, the App or use our services.
          </p>
          
          <h2 className="text-2xl font-semibold mt-8 mb-4">Interpretation and Definitions</h2>
          
          <h3 className="text-xl font-semibold mt-6 mb-3">Interpretation</h3>
          <p>
            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>
          
          <h3 className="text-xl font-semibold mt-6 mb-3">Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          
          <p><strong>Account</strong> means the account that each User must apply for to use the Femride App to access our Services.</p>
          
          <p><strong>Application</strong> means the software program provided by the Company downloaded by You on any electronic device, named Femride App</p>
          
          <p><strong>Company</strong> (referred to as either "Femride", "the Company", "We", "Us" or "Our" in this Agreement) refers to Femride Company Limited (Company Registration Number C63326), 4, Salvu Aquilina Street, Mosta. For the purpose of the GDPR, the Company is the Data Controller.</p>
          
          <p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
          
          <p><strong>Data Controller</strong>, for the purposes of the GDPR (General Data Protection Regulation), refers to the Company as the legal person which alone or jointly with others determines the purposes and means of the processing of Personal Data.</p>
          
          <p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
          
          <p><strong>Facebook Page</strong> is a public profile named 'Femride' specifically created by the Company on the Facebook social network, accessible from www.facebook.com/Femride</p>
          
          <p><strong>Group Company</strong> means an entity that forms part of the Femride Group.</p>
          
          <p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual as outlined in 'Types of Data Collected' below</p>
          
          <p><strong>Service</strong> refers to the Application or the Website or both. Service shall include the term 'Femride Services' as defined in the Terms and Conditions.</p>
          
          <p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used. For the purpose of the GDPR, Service Providers are considered Data Processors. This shall include third party Drivers.</p>
          
          <p><strong>User</strong> refers to anyone who downloads the Femride App.</p>
          
          <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
          
          <p><strong>Website</strong> refers to www.femride.de</p>
          
          <p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
          
          <p>Under GDPR (General Data Protection Regulation), You can be referred to as the Data Subject or as the User as you are the individual using the Service.</p>
          
          <h2 className="text-2xl font-semibold mt-8 mb-4">Collecting and Using Your Personal Data</h2>
          
          <h3 className="text-xl font-semibold mt-6 mb-3">Types of Data Collected</h3>
          
          <h4 className="text-lg font-semibold mt-4 mb-2">Personal Data</h4>
          <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
          <ul className="list-disc pl-6 mt-2 mb-4">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address and other booking way points</li>
            <li>Credit Card information in order to pay for products and/or services within the Service</li>
            <li>Device Token and Usage Data</li>
            <li>Advertising identifiers from device</li>
            <li>Passenger information such as Name, Surname and Phone Number.</li>
          </ul>
          
          <p>When You pay for a product and/or a service via bank transfer, We may ask You to provide information to facilitate this transaction and to verify Your identity. Such information may include, without limitation:</p>
          <ul className="list-disc pl-6 mt-2 mb-4">
            <li>Date of birth</li>
            <li>Passport or National ID card</li>
            <li>Bank card statement</li>
            <li>Other information linking You to an address</li>
          </ul>
          
          <p>When a booking is confirmed, details are recorded securely on the Femride booking system which is hosted by a third party. This data is held on the Femride server, which is hosted by a third-party who is bound by the same data protection duties and GDPR law as is Femride. Such data may be anonymized.</p>
          
          <h4 className="text-lg font-semibold mt-4 mb-2">Usage Data</h4>
          <p>Usage Data is collected automatically when using the Service.</p>
          
          <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
          
          <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
          
          <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
          
          <h4 className="text-lg font-semibold mt-4 mb-2">Information Collected while Using the Application</h4>
          <p>While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:</p>
          <ul className="list-disc pl-6 mt-2 mb-4">
            <li>Information regarding your location</li>
          </ul>
          
          <p>We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.</p>
          
          <p>When you use one of Our location-enabled services, we may collect and process information about your actual location. Our services require your personal location data for the feature to work. Your consent can be withdrawn at any time by switching off the location-based services on your Device however we cannot guarantee that We will be able of offer the Service. If you require further details of how we use location-based services, you can request such information by contacting our Data Processing Officer on info@femride.de.</p>
          
          <h4 className="text-lg font-semibold mt-4 mb-2">Loyalty Scheme</h4>
          <p>When using Our Application, you benefit from our loyalty scheme ("Femride Circle) meaning you authorise us to process and store your data necessary for the functioning of the loyalty scheme. This shall be limited to the information your supplied when signing up following the installation of the Application.</p>
          
          <h3 className="text-xl font-semibold mt-6 mb-3">Tracking Technologies and Cookies</h3>
          <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
          
          <ul className="list-disc pl-6 mt-2 mb-4">
            <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
            <li><strong>Flash Cookies.</strong> Certain features of our Service may use local stored objects (or Flash Cookies) to collect and store information about Your preferences or Your activity on our Service. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies.</li>
            <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
          </ul>
          
          <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
          
          <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
          
          <p><strong>Necessary / Essential Cookies</strong></p>
          <p>Type: Session Cookies</p>
          <p>Administered by: Us</p>
          <p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
          
          <p><strong>Cookies Policy / Notice Acceptance Cookies</strong></p>
          <p>Type: Persistent Cookies</p>
          <p>Administered by: Us</p>
          <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
          
          <p><strong>Functionality Cookies</strong></p>
          <p>Type: Persistent Cookies</p>
          <p>Administered by: Us</p>
          <p>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
          
          <p><strong>Tracking and Performance Cookies</strong></p>
          <p>Type: Persistent Cookies</p>
          <p>Administered by: Third-Parties</p>
          <p>Purpose: These Cookies are used to track information about traffic to the Website and how users use the Website. The information gathered via these Cookies may directly or indirectly identify you as an individual visitor. This is because the information collected is typically linked to a pseudonymous identifier associated with the device you use to access the Website. We may also use these Cookies to test new pages, features or new functionality of the Website to see how our users react to them.</p>
          
          <h3 className="text-xl font-semibold mt-6 mb-3">Use of Your Personal Data</h3>
          <p>The Company may use Personal Data for the following purposes:</p>
          
          <ul className="list-disc pl-6 mt-2 mb-4">
            <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service and the ensuring that the content on Our site and Application are presented in the most effective manner for You and your device.</li>
            <li><strong>To manage Your Account</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
            <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the carrying out of Our obligations arising from any booking you have made with Us which may include the sharing of such data with third party processors.</li>
            <li><strong>To contact You</strong> by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
            <li><strong>To provide You</strong> with information, products or services that you request from us or which we feel may interest you, where (if required to do so) you have consented to be contacted for such purposes unless You have opted not to receive such information.</li>
            <li><strong>To manage Your requests</strong> by creating records of bookings and to sending You booking acknowledgments, confirmations, invoices and statements.</li>
            <li><strong>To deliver targeted advertising to You</strong> We may use Your information to develop and display content and advertising (and work with third-party vendors who do so) tailored to Your interests and/or location and to measure its effectiveness.</li>
            <li><strong>For business transfers</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
            <li><strong>For other purposes</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
            <li><strong>For our loyalty scheme</strong> known as Femride Circle or as renamed from time to time and for insurance purposes.</li>
            <li><strong>To notify you</strong> about updated and changes to Our service.</li>
            <li><strong>To meet customer service requirements</strong> and for complaint handling and feedback.</li>
          </ul>
          
          <p>We will only contact you by electronic means (e-mail or SMS) with information about updates, goods and services similar to those which We have previously supplied to you. If you do not want us to use your data in this way, please let We know by contacting our Data Processing Officer on info@femride.de. We may also use and analyse the aggregate (collective data that relates to a group or category of services or customers, from which individual customer identities or characteristics have been removed) information collected through the analytics provision so that We can administer, support, improve and develop their business.</p>
          
          <p>We only work with trusted partners and authorities. We only share when there is a proper reason to do so. We limit sharing to only that which is required. We do not sell your personal information.</p>
          
          <p>We may share Your personal information in the following situations:</p>
          
          <ul className="list-disc pl-6 mt-2 mb-4">
            <li><strong>With Third Party Providers</strong> to provide the service such as with drivers and fleet operators. These shall include services providers relating to payment processing, storage, marketing agencies, professionals, social media platform providers for our own marketing and research partners.</li>
            <li><strong>For business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
            <li><strong>With Group Companies:</strong> We may share Your information with Our Group Companies, in which case we will require those Group Companies to honor this Privacy Policy. Group companies include companies which We control or that are under common control with Us.</li>
            <li><strong>With business partners:</strong> We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
            <li><strong>With Your consent:</strong> We may disclose Your personal information for any other purpose with Your consent.</li>
            <li><strong>Legally Bound to do so:</strong> if We are under a duty to disclose or share your personal data in order to comply with any legal obligation, process or request or in order to enforce or apply our terms and conditions and/or any other agreements; or to protect the rights, property, or safety of the Company, our customers, or others (this includes exchanging information with other companies and organisations for the purposes of fraud protection and credit risk reduction).</li>
          </ul>
          
          <h3 className="text-xl font-semibold mt-6 mb-3">Retention of Your Personal Data</h3>
          <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
          
          <p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>
          
          <p>In order to determine the retention period of your Personal Data, we consider several criteria so that your personal data is not kept for longer than necessary. Such criteria include but are not limited to;</p>
          
          <ul className="list-disc pl-6 mt-2 mb-4">
            <li>the reason we hold your personal data;</li>
            <li>statutory obligations including the Laws of Malta and Transport Malta Regulations (we also adhere to any financial reporting obligations);</li>
            <li>whether we deem you to be a regular client, which classification is based on the services you request from us, whether you have chosen to receive our marketing communications and whether you have our App installed;</li>
            <li>whether you are no longer actively participating or engaging with us and whether you have requested Us to delete or alter your data; and</li>
            <li>our legitimate business interests in relation to managing our own rights, for example the defence of any claims.</li>
          </ul>
          
          <p>We will retain your information as follows:</p>
          
          <ul className="list-disc pl-6 mt-2 mb-4">
            <li>In case of payment disputes, data will be retained until the claim is satisfied or the expiry date of such claims.</li>
            <li>your user profile and account information (including your technical usage data), for as you have an active passenger account or 3 years after you last use our services. If we close your account, user data will be deleted in terms of our retention policy, unless such data is still required to meet any legal obligation, or for accounting, dispute resolution or fraud prevention purposes.</li>
            <li>In case of payment disputes, data will be retained until the claim is satisfied or the expiry date of such claims.</li>
            <li>records of bookings, lost property and complaints for a minimum of 12 months or as per statutory requirements.</li>
            <li>Data required for other accounting purposes will be stored for ten years after the last journey.</li>
            <li>In the event of a suspected criminal offence, fraudulent activity or false information having been provided, all data will be stored for up to 10 years.</li>
          </ul>
          
          <h3 className="text-xl font-semibold mt-6 mb-3">Storage & Transfer of Your Personal Data</h3>
          <p>The data that we collect from you may be stored on the Femride servers situated inside the European Economic Area (EEA). Where necessary it may be transferred to third parties for processing in line with our agreements with such third parties. We require all third parties to whom we disclose personal data to enter into a contract with us which includes stringent confidentiality obligations.</p>
          
          <p>Your data may also be processed by staff who work for us or for one of our suppliers. Such staff may be engaged in, among other things, the fulfilment of your order and the provision of support services. By submitting your personal data, you agree to this transfer, storing or processing. We will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this privacy policy and relevant regulations. Once we have received your information, we will use strict procedures and security features to prevent unauthorised access.</p>
          
          <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
          
          <h3 className="text-xl font-semibold mt-6 mb-3">Disclosure of Your Personal Data</h3>
          
          <h4 className="text-lg font-semibold mt-4 mb-2">Business Transactions</h4>
          <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
          
          <h4 className="text-lg font-semibold mt-4 mb-2">Law enforcement</h4>
          <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
          
          <h4 className="text-lg font-semibold mt-4 mb-2">Other legal requirements</h4>
          <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
          
          <ul className="list-disc pl-6 mt-2 mb-4">
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of the Company</li>
            <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>Protect the personal safety of Users of the Service or the public</li>
            <li>Protect against legal liability</li>
          </ul>
          
          <h3 className="text-xl font-semibold mt-6 mb-3">Security of Your Personal Data</h3>
          <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
          
          <h2 className="text-2xl font-semibold mt-8 mb-4">Detailed Information on the Processing of Your Personal Data</h2>
          
          <p>The Service Providers We use may have access to Your Personal Data. These third-party vendors collect, store, use, process and transfer information about Your activity on Our Service in accordance with their Privacy Policies.</p>
          
          <h3 className="text-xl font-semibold mt-6 mb-3">Analytics</h3>
          <p>We may use third-party Service providers to monitor and analyze the use of our Service.</p>
          
          <p><strong>Google Analytics</strong></p>
          
          <p>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.</p>
          
          <p>You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js and dc.js) from sharing information with Google Analytics about visits activity.</p>
          
          <p>You may opt-out of certain Google Analytics features through your mobile device settings, such as your device advertising settings or by following the instructions provided by Google in their Privacy Policy: https://policies.google.com/privacy</p>
          
          <p>For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: https://policies.google.com/privacy</p>
          
          <h3 className="text-xl font-semibold mt-6 mb-3">Email Marketing</h3>
          <p>We may use Your Personal Data to contact You with newsletters, marketing or promotional materials and other information that may be of interest to You. You may opt-out of receiving any, or all, of these communications from Us by following the unsubscribe link or instructions provided in any email We send or by contacting Us.</p>
          
          <p>We may use Email Marketing Service Providers to manage and send emails to You.</p>
          
          <p><strong>MailerSend</strong></p>
          
          <p>MailerSend is an email marketing sending service.</p>
          
          <h3 className="text-xl font-semibold mt-6 mb-3">Payments</h3>
          <p>We may provide paid products and/or services within the Service. In that case, we may use third-party services for payment processing (e.g. payment processors).</p>
          
          <p>We will not store or collect Your payment card details. That information is provided directly to Our third-party payment processors whose use of Your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</p>
          
          <p><strong>Apple Store In-App Payments</strong></p>
          
          <p>Their Privacy Policy can be viewed at https://www.apple.com/legal/privacy/en-ww/</p>
          
          <p><strong>Google Play In-App Payments</strong></p>
          
          <p>Their Privacy Policy can be viewed at https://www.google.com/policies/privacy/</p>
          
          <p>When You use Our Service to pay a product and/or service via bank transfer, We may ask You to provide information to facilitate this transaction and to verify Your identity.</p>
          
          <h3 className="text-xl font-semibold mt-6 mb-3">Behavioral Remarketing</h3>
          <p>The Company uses remarketing services to advertise to You after You accessed or visited our Service. We and Our third-party vendors use cookies and non-cookie technologies to help Us recognize Your Device and understand how You use our Service so that We can improve our Service to reflect Your interests and serve You advertisements that are likely to be of more interest to You.</p>
          
          <p>These third-party vendors collect, store, use, process and transfer information about Your activity on Our Service in accordance with their Privacy Policies and to enable Us to:</p>
          
          <ul className="list-disc pl-6 mt-2 mb-4">
            <li>Measure and analyze traffic and browsing activity on Our Service</li>
            <li>Show advertisements for our products and/or services to You on third-party websites or apps</li>
            <li>Measure and analyze the performance of Our advertising campaigns</li>
          </ul>
          
          <p>Some of these third-party vendors may use non-cookie technologies that may not be impacted by browser settings that block cookies. Your browser may not permit You to block such technologies. You can use the following third-party tools to decline the collection and use of information for the purpose of serving You interest-based advertising:</p>
          
          <ul className="list-disc pl-6 mt-2 mb-4">
            <li>The NAI's opt-out platform: http://www.networkadvertising.org/choices/</li>
            <li>The EDAA's opt-out platform http://www.youronlinechoices.com/</li>
            <li>The DAA's opt-out platform: http://optout.aboutads.info/?c=2&lang=EN</li>
          </ul>
          
          <p>You may opt-out of all personalized advertising by enabling privacy features on Your mobile device such as Limit Ad Tracking (iOS) and Opt Out of Ads Personalization (Android). See Your mobile device Help system for more information.</p>
          
          <p>We may share information, such as hashed email addresses (if available) or other online identifiers collected on Our Service with these third-party vendors. This allows Our third-party vendors to recognize and deliver You ads across devices and browsers. To read more about the technologies used by these third-party vendors and their cross-device capabilities please refer to the Privacy Policy of each vendor listed below.</p>
          
          <p>The third-party vendors We use are:</p>
          
          <p><strong>Google Ads (AdWords)</strong></p>
          
          <p>Google Ads (AdWords) remarketing service is provided by Google Inc.</p>
          
          <p>You can opt-out of Google Analytics for Display Advertising and customise the Google Display Network ads by visiting the Google Ads Settings page: http://www.google.com/settings/ads</p>
          
          <p>Google also recommends installing the Google Analytics Opt-out Browser Add-on – https://tools.google.com/dlpage/gaoptout – for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics.</p>
          
          <p>For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: https://policies.google.com/privacy</p>
          
          <p><strong>Facebook</strong></p>
          
          <p>Facebook remarketing service is provided by Facebook Inc.</p>
          
          <p>You can learn more about interest-based advertising from Facebook by visiting this page: https://www.facebook.com/help/516147308587266</p>
          
          <p>To opt-out from Facebook's interest-based ads, follow these instructions from Facebook: https://www.facebook.com/help/568137493302217</p>
          
          <p>Facebook adheres to the Self-Regulatory Principles for Online Behavioural Advertising established by the Digital Advertising Alliance. You can also opt-out from Facebook and other participating companies through the Digital Advertising Alliance in the USA http://www.aboutads.info/choices/, the Digital Advertising Alliance of Canada in Canada http://youradchoices.ca/ or the European Interactive Digital Advertising Alliance in Europe http://www.youronlinechoices.eu/, or opt-out using your mobile device settings.</p>
          
          <p>For more information on the privacy practices of Facebook, please visit Facebook's Data Policy: https://www.facebook.com/privacy/explanation</p>
          
          <p><strong>Youtube</strong></p>
          
          <p>Their Privacy Policy can be viewed at https://www.youtube.com/static?template=terms</p>
          
          <h2 className="text-2xl font-semibold mt-8 mb-4">GDPR Privacy</h2>
          
          <h3 className="text-xl font-semibold mt-6 mb-3">Legal Basis for Processing Personal Data under GDPR</h3>
          <p>We may process Personal Data under the following conditions:</p>
          
          <ul className="list-disc pl-6 mt-2 mb-4">
            <li><strong>Consent:</strong> You have given Your consent for processing Personal Data for one or more specific purposes.</li>
            <li><strong>Performance of a contract:</strong> Provision of Personal Data is necessary for the performance of an agreement with You and/or for any pre-contractual obligations thereof.</li>
            <li><strong>Legal obligations:</strong> Processing Personal Data is necessary for compliance with a legal obligation to which the Company is subject.</li>
            <li><strong>Vital interests:</strong> Processing Personal Data is necessary in order to protect Your vital interests or of another natural person.</li>
            <li><strong>Public interests:</strong> Processing Personal Data is related to a task that is carried out in the public interest or in the exercise of official authority vested in the Company.</li>
            <li><strong>Legitimate interests:</strong> Processing Personal Data is necessary for the purposes of the legitimate interests pursued by the Company.</li>
          </ul>
          
          <p>In any case, the Company will gladly help to clarify the specific legal basis that applies to the processing, and in particular whether the provision of Personal Data is a statutory or contractual requirement, or a requirement necessary to enter into a contract.</p>
          
          <h3 className="text-xl font-semibold mt-6 mb-3">Your Rights under the GDPR</h3>
          <p>The Company undertakes to respect the confidentiality of Your Personal Data and to guarantee You can exercise Your rights.</p>
          
          <p>You have the right under this Privacy Policy, and by law if You are within the EU, to:</p>
          
          <ul className="list-disc pl-6 mt-2 mb-4">
            <li><strong>Request access to Your Personal Data.</strong> The right to access, update or delete the information We have on You. Whenever made possible, you can access, update or request deletion of Your Personal Data directly within Your account settings section. If you are unable to perform these actions yourself, please contact Us to assist You. This also enables You to receive a copy of the Personal Data We hold about You.</li>
            <li><strong>Request correction of the Personal Data that We hold about You.</strong> You have the right to have any incomplete or inaccurate information We hold about You corrected.</li>
            <li><strong>Object to processing of Your Personal Data.</strong> This right exists where We are relying on a legitimate interest as the legal basis for Our processing and there is something about Your particular situation, which makes You want to object to our processing of Your Personal Data on this ground. You also have the right to object where We are processing Your Personal Data for direct marketing purposes.</li>
            <li><strong>Request erasure of Your Personal Data.</strong> You have the right to ask Us to delete or remove Personal Data when there is no good reason for Us to continue processing it.</li>
            <li><strong>Request the transfer of Your Personal Data.</strong> We will provide to You, or to a third-party You have chosen, Your Personal Data in a structured, commonly used, machine-readable format. Please note that this right only applies to automated information which You initially provided consent for Us to use or where We used the information to perform a contract with You.</li>
            <li><strong>Withdraw Your consent.</strong> You have the right to withdraw Your consent on using your Personal Data. If You withdraw Your consent, We may not be able to provide You with access to certain specific functionalities of the Service.</li>
          </ul>
          
          <p>Uninstalling the App does not mean that we will delete your data automatically. You must still request that we delete your data and such request shall be entertained limitedly to the data we are not obliged to retain.</p>
          
          <h3 className="text-xl font-semibold mt-6 mb-3">Exercising of Your GDPR Data Protection Rights</h3>
          <p>You may exercise Your rights of access, rectification, cancellation and opposition by contacting Us. Please note that we may ask You to verify Your identity before responding to such requests. If You make a request, We will try our best to respond to You as soon as possible.</p>
          
          <p>You can exercise any of your rights by contacting our Data Processing Officer on info@femride.de.</p>
          
          <p>You have the right to complain to a Data Protection Authority about Our collection and use of Your Personal Data. For more information, if You are in the European Economic Area (EEA), please contact Your local data protection authority in the EEA.</p>
          
          <h2 className="text-2xl font-semibold mt-8 mb-4">Facebook Page</h2>
          
          <h3 className="text-xl font-semibold mt-6 mb-3">Data Controller for the Facebook Page</h3>
          <p>The Company is the Data Controller of Your Personal Data collected while using the Service. As operator of the Facebook Page www.facebook.com/Femride, the Company and the operator of the social network Facebook are Joint Controllers.</p>
          
          <p>The Company has entered into agreements with Facebook that define the terms for use of the Facebook Page, among other things. These terms are mostly based on the Facebook Terms of Service: www.facebook.com/terms.php</p>
          
          <p>Visit the Facebook Privacy Policy www.facebook.com/policy.php for more information about how Facebook manages Personal data or contact Facebook online, or by mail: Facebook, Inc. ATTN, Privacy Operations, 1601 Willow Road, Menlo Park, CA 94025, United States.</p>
          
          <h3 className="text-xl font-semibold mt-6 mb-3">Facebook Insights</h3>
          <p>We use the Facebook Insights function in connection with the operation of the Facebook Page and on the basis of the GDPR, in order to obtain anonymized statistical data about Our users.</p>
          
          <p>For this purpose, Facebook places a Cookie on the device of the user visiting Our Facebook Page. Each Cookie contains a unique identifier code and remains active for a period of two years, except when it is deleted before the end of this period.</p>
          
          <p>Facebook receives, records and processes the information stored in the Cookie, especially when the user visits the Facebook services, services that are provided by other members of the Facebook Page and services by other companies that use Facebook services.</p>
          
          <p>For more information on the privacy practices of Facebook, please visit Facebook Privacy Policy here: https://www.facebook.com/privacy/explanation</p>
          
          <h2 className="text-2xl font-semibold mt-8 mb-4">Links to Other Websites</h2>
          
          <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
          
          <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
          
          <h2 className="text-2xl font-semibold mt-8 mb-4">Changes to this Privacy Policy</h2>
          
          <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
          
          <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
          
          <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
          
          <h2 className="text-2xl font-semibold mt-8 mb-4">Contact Us</h2>
          
          <p>Questions, comments and requests regarding this privacy policy are welcomed and should be addressed to the Data Processing Officer on info@femride.de.</p>
          
          <p>The supervisory authority is the Office of the Information and Data Protection Commissioner which can be contacted at Level 2, Airways House, High Street, Sliema SLM 1549, Malta or by telephone on (+356) 2328 7100 or by email at idpc.info@idpc.org.mt</p>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default PrivacyPolicy;
